title               : Shashank Benakatti
description         : >-                               # >- means to ignore newlines until "url:"
                     Hey , I am Shashank. A 3rd Year Student pursuing Computer Science at the Manipal Institute of Technology, Bengaluru Campus.


url                 : "https://vyshnav2255.github.io/"
repository          : Vyshnav2255/Minimal-Portfolio-Website 

email: bob525test@gmail.com
github_user: shashank60
instagram: shashank_.b
twitter: shashankb18
dribbble: google.com

exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock